package com.jakubfilo.peopleservice.domain;

public enum NotificationType {
	COURSE_ADDED,
	COURSE_REMOVED,
	COURSE_SCHEDULE_CHANGED,
	GENERAL_ANNOUNCEMENT,
	STUDENT_COURSE_ENROLLMENT,
	STUDENT_GRADES_PUBLISHED
}
